# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# name: Playwright Tests

# trigger:
# - main

# jobs:
#   - job: test
#     timeoutInMinutes: 60
# #     pool:
# #       vmImage: ubuntu-latest

#     steps:
#       - task: NodeTool@0
#         inputs:
#           versionSpec: '16.x'
#         displayName: 'Install Node.js'

#       - script: |
#           npm ci
#         displayName: "Install dependencies"

#       - script: |
#           npx playwright install --with-deps
#         displayName: "Install Playwright Browsers"

#       - script: |
#           npm test
#         displayName: "Run Playwright tests"

#       - publish: $(System.DefaultWorkingDirectory)/playwright-report
#         artifact: playwright-report
#         # always create the artifact, this is useful for debugging failed tests
#         condition: always()
jobs:
    - deployment: Run_E2E_Tests
      pool:
        vmImage: ubuntu-20.04
      container: mcr.microsoft.com/playwright:v1.31.0-focal
      environment: testing
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: Bash@3
              displayName: 'Run Playwright tests'
              inputs:
                workingDirectory: 'my-e2e-tests'
                targetType: 'inline'
                failOnStderr: true
                env:
                  CI: true
                script: |
                  npm ci
                  npx playwright test
